// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Ingredient
{
	private string name;
	private bool liquid;
	private Color drinkColor;
	
	public Ingredient(string name, bool liquid, Color color){
		this.name = name;
		this.isLiquid = liquid;
		this.drinkColor = color;
	}

	public string getName() {
		return this.name;
	}

	public bool isLiquid() {
		return this.liquid;
	}

	public Color getDrinkColor() {
		return this.drinkColor;
	}
}
